import { Container, Grid, Loading, Button } from '@nextui-org/react';
import type { NextPage, NextPageContext } from 'next';
import Head from 'next/head';
import { useQuery } from 'react-query';
import ProfileCard from '../../components/profile-card';
import {
  GetProfiles,
  GetUserProfile
} from '../../shared/services/internal-service';
import { useProfiles } from '../../shared/hooks/useProfile.hook';
import { getSession, signOut, useSession } from 'next-auth/react';
import { unstable_getServerSession } from 'next-auth';
import { authOptions } from '../api/auth/[...nextauth]';
import db from '../../shared/services/prisma.service';
import { useEffect } from 'react';
import { NextDnsApi } from '../../shared/datasources/base-api';
import { SSP_UserApiKey } from '../../shared/helpers/apikey.helper';

type Props = {
  apiKey: string;
};

const Home: NextPage<Props> = ({ apiKey }) => {
  const { setUserProfiles } = useProfiles();

  const { isLoading, data = [] } = useQuery(
    'Profiles',
    async () => await GetProfiles(),
    {
      onSuccess: (data) => {
        setUserProfiles(data);
      }
    }
  );

  return (
    <div>
      <Head>
        <title>NextDNS Monitor | Profiles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container css={{ height: '100%' }}>
        <Grid.Container
          css={{ height: 'stretch' }}
          gap={2}
          justify="center"
          alignItems="center"
        >
          {isLoading ? (
            <Loading size="lg" />
          ) : (
            data &&
            data.map((profile) => (
              <Grid xs={4} key={profile.id}>
                <ProfileCard {...profile} />
              </Grid>
            ))
          )}

          <Button onClick={() => signOut({ redirect: true, callbackUrl: '/' })}>
            Sign Out
          </Button>
        </Grid.Container>
      </Container>
    </div>
  );
};

export default Home;

export async function getServerSideProps(ctx: any) {
  // const profile = await SSP_UserApiKey(ctx);

  return {
    props: {
      // apiKey: profile?.apiKey
    }
  };
}
