import { Container, Grid, Spinner } from '@nextui-org/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useProfiles } from '../shared/hooks/useProfile.hook';
import Auth from '../components/auth';
import { signIn, useSession } from 'next-auth/react';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const { setUserProfiles } = useProfiles();
  const session = useSession();
  const router = useRouter();
  useEffect(() => {
    switch (session.status) {
      case 'authenticated':
        router.push('/profiles');
        break;
    }
  }, [session.status, router]);
  return (
    <div>
      <Head>
        <title>NextDNS Monitor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container css={{ height: '100%' }}>
        {session.status === 'loading' ? <Spinner /> : null}
      </Container>
    </div>
  );
};

export default Home;
